"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BarChart3, Ear, MessageSquare, PenLine } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface Metric { seen: number; correct: number; percent: number | null }
interface Data { total: number; reviewed: number; mastered: number; weakReduced: number; production: Metric; listening: Metric; recent: { attempts: number; correct: number; naturalTutorUses: number }; readiness: { productionEvidence: number; listeningEvidence: number; conversationEvidence: number; note: string } }
function Accuracy({ name, icon: Icon, metric }: { name: string; icon: typeof Ear; metric: Metric }) { return <Card><CardContent className="p-5"><Icon className="mb-3 h-5 w-5 text-muted-foreground"/><div className="text-3xl font-semibold">{metric.percent === null ? "—" : `${metric.percent}%`}</div><div className="font-medium">{name}</div><div className="text-xs text-muted-foreground">{metric.correct} correct of {metric.seen} attempts</div></CardContent></Card>; }
export default function ProgressPage() { const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); useEffect(() => { fetch("/api/analytics", { cache: "no-store" }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); return d; }).then(setData).catch(e => setError(String(e))); }, []); return <main className="container max-w-3xl py-7">
  <Link href="/" className="mb-5 inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Home</Link><h1 className="text-3xl font-semibold">Learning picture</h1><p className="mb-6 text-muted-foreground">Evidence from your personal lesson French—no points or streak pressure.</p>
  {!data ? error ? <p className="text-destructive">{error}</p> : <div className="h-52 animate-pulse rounded-xl bg-muted"/> : <>
    <div className="grid grid-cols-2 gap-3"><Accuracy name="Production" icon={PenLine} metric={data.production}/><Accuracy name="Listening" icon={Ear} metric={data.listening}/></div>
    <div className="mt-3 grid grid-cols-3 overflow-hidden rounded-xl border bg-card text-center"><div className="p-4"><div className="text-2xl font-semibold">{data.reviewed}</div><div className="text-xs text-muted-foreground">reviewed</div></div><div className="border-x p-4"><div className="text-2xl font-semibold">{data.mastered}</div><div className="text-xs text-muted-foreground">mastered</div></div><div className="p-4"><div className="text-2xl font-semibold">{data.weakReduced}</div><div className="text-xs text-muted-foreground">weak reduced</div></div></div>
    <Card className="mt-5"><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5"/>Last 30 days</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-3 text-center"><div><b>{data.recent.attempts}</b><div className="text-xs text-muted-foreground">attempts</div></div><div><b>{data.recent.correct}</b><div className="text-xs text-muted-foreground">successful</div></div><div><b>{data.recent.naturalTutorUses}</b><div className="text-xs text-muted-foreground">natural tutor uses</div></div></CardContent></Card>
    <Card className="mt-5"><CardHeader><CardTitle className="flex items-center gap-2"><MessageSquare className="h-5 w-5"/>TCF / NCLC readiness evidence</CardTitle></CardHeader><CardContent><div className="grid grid-cols-3 gap-2 text-center text-sm"><div>{data.readiness.productionEvidence}<div className="text-xs text-muted-foreground">written production</div></div><div>{data.readiness.listeningEvidence}<div className="text-xs text-muted-foreground">listening</div></div><div>{data.readiness.conversationEvidence}<div className="text-xs text-muted-foreground">real uses</div></div></div><p className="mt-4 text-xs text-muted-foreground">{data.readiness.note} Use a timed mock or official test for level decisions.</p></CardContent></Card>
  </>}
  </main>; }
