import type { ErrorTag, Topic } from "./types";

type Entry = [string, string, Topic["coverage"], string, ErrorTag[], number?, string[]?];
const groups: Record<string, Entry[]> = {
  "Articles": [
    ["definite-articles", "Definite articles · le, la, l’, les", "practiced", "Specific nouns and general preferences: J’aime le lait. Mix article types.", ["ARTICLE_SELECTION"]],
    ["indefinite-articles", "Indefinite articles · un, une, des", "practiced", "Gender and number. Mix with definite and partitive; avoid endless isolated drills.", ["ARTICLE_SELECTION", "GENDER_NUMBER_AGREEMENT"]],
    ["partitives", "Partitive articles", "practiced", "Unspecified quantities: du lait, de la soupe, des légumes. Contrast general liking with actual quantities.", ["ARTICLE_SELECTION"]],
    ["article-negation", "Articles after negation", "partial", "High-priority weakness: un/une/des/du/de la → de/d’ after negation; definite articles stay. Include the être exception gradually. Je ne bois pas de lait / Je n’aime pas le lait.", ["ARTICLE_NEGATION"], 100],
  ],
  "Verbs & tenses": [
    ["present", "Present tense", "practiced", "Regular and common irregular verbs; actions, habits and states. Full sentences, not another long introduction.", ["VERB_FORM"], 40],
    ["etre-avoir", "Être or avoir?", "practiced", "Possession, age, hunger and thirst use avoir. J’ai une sœur / Je suis ingénieur. Also auxiliary selection.", ["ETRE_AVOIR"], 95],
    ["negation", "Basic negation", "practiced", "Placement in present, passé composé and futur proche. Je n’ai pas travaillé / Je ne vais pas travailler.", ["VERB_FORM"]],
    ["cest-ce-sont", "C’est / ce sont", "practiced", "Singular vs plural identification. Occasional mixed retrieval.", ["GENDER_NUMBER_AGREEMENT"]],
    ["pc-avoir", "Passé composé with avoir", "practiced", "Avoir + participle. Gradually automate fait, pris, dit, vu, lu, eu, été, bu, écrit, reçu.", ["VERB_FORM", "ETRE_AVOIR"]],
    ["pc-etre", "Passé composé with être", "partial", "Some movement/change-of-state verbs and reflexives; not all movement verbs. Auxiliary choice, then subject agreement.", ["ETRE_AVOIR"], 65],
    ["pc-agreement", "Past participle agreement with être", "partial", "Allé/allée/allés/allées: subject gender and number. Avoid advanced reflexive exceptions initially.", ["GENDER_NUMBER_AGREEMENT"], 75],
    ["reflexive-present", "Reflexive verbs · present", "partial", "Je me réveille, je m’entraîne, elle se lève. Pronoun placement and conjugation.", ["REFLEXIVE_VERBS", "PRONOUN_PLACEMENT"], 65],
    ["reflexive-past", "Reflexive verbs · past", "partial", "Je me suis réveillé, je me suis entraîné. Reflexive pronoun + être + participle; gender made explicit.", ["REFLEXIVE_VERBS", "ETRE_AVOIR"], 65],
    ["imparfait-form", "Imparfait formation", "practiced", "Nous present stem minus -ons; -ais/-ais/-ait/-ions/-iez/-aient. Être uses ét-. Full sentence retrieval.", ["VERB_FORM"]],
    ["imparfait-use", "When to use imparfait", "partial", "Background, habitual or ongoing past, states and descriptions. Never reduce the rule to English ‘used to’.", ["PC_IMPARFAIT"], 80],
    ["pc-imparfait", "Passé composé vs imparfait", "partial", "Major active topic. Contrast both tenses in one story: Je mangeais quand mon ami m’a appelé. Context must disambiguate.", ["PC_IMPARFAIT"], 100],
    ["futur-proche", "Futur proche", "practiced", "Conjugated aller + infinitive; only aller is conjugated. Future plans and negation.", ["VERB_FORM"]],
    ["second-infinitive", "Infinitive after a verb", "practiced", "Je veux manger / Je vais travailler / J’aime jouer. Keep review natural and brief.", ["VERB_FORM"]],
    ["imperative", "Imperative", "new", "Tu/nous/vous commands; negation; sois/soyez, aie/ayez, va/allez. Real instructions. Delay complex affirmative pronoun order.", ["VERB_FORM"], 85],
    ["futur-simple", "Futur simple", "new", "Only exposed, never systematically learned. Infinitive + ai/as/a/ons/ez/ont; -re drops e. ser/aur/ir/fer/viendr/pourr/voudr/devr. Contrast future forms without rigid near/far rules.", ["VERB_FORM"], 80, ["futur-proche"]],
    ["passe-recent", "Passé récent", "new", "Venir de + infinitive: Je viens de manger. I have just done something.", ["VERB_FORM"], 70],
    ["en-train-de", "Être en train de", "new", "An action in progress, être en train de + infinitive. Contrast ordinary present with emphasis on being in the middle of something.", ["VERB_FORM"], 65],
    ["il-y-a", "Il y a", "new", "Encountered only. There is/are, questions and negation il n’y a pas de. Teach separately from ago initially.", ["ARTICLE_NEGATION", "VERB_FORM"], 60],
  ],
  "Pronouns & possessives": [
    ["possessive-adjectives", "Possessive adjectives", "practiced", "Mon/ma/mes etc agree with the thing possessed, not owner. Marie aime son frère. Revisit leur vs leurs.", ["POSSESSIVE_AGREEMENT"]],
    ["possessive-vowels", "Mon amie · vowel rule", "practiced", "Ma/ta/sa → mon/ton/son before feminine singular vowel or silent h. Occasional review.", ["POSSESSIVE_AGREEMENT"]],
    ["possessive-pronouns", "Possessive pronouns", "partial", "Le mien/la mienne/les miens/les miennes; le tien/sien/nôtre/vôtre/leur. Gender, number and adjective vs pronoun distinction.", ["POSSESSIVE_AGREEMENT"], 70],
    ["demonstrative-adjectives", "Ce, cet, cette, ces", "partial", "Cet before masculine singular vowel/silent h: cet appartement. Mixed full-sentence production.", ["GENDER_NUMBER_AGREEMENT"]],
    ["direct-objects", "Direct object pronouns", "new", "FIRST new topic. Me/te/le/la/nous/vous/les before conjugated verb. Transform Paul/Marie/apple/shoes; then negatives. Do not introduce past-participle agreement initially; later Je l’ai achetée needs agreement explained.", ["PRONOUN_SELECTION", "PRONOUN_PLACEMENT"], 100],
    ["indirect-objects", "Indirect object pronouns", "new", "Me/te/lui/nous/vous/leur for suitable verbs with à + person. Parler/téléphoner/écrire. Contrast je la regarde vs je lui parle; not every à verb takes lui.", ["PRONOUN_SELECTION", "PRONOUN_PLACEMENT"], 98, ["direct-objects"]],
    ["pronoun-y", "Y", "new", "Replace locations and appropriate à + things: J’y vais, j’y pense. Do not overload exceptions.", ["PRONOUN_SELECTION", "PRONOUN_PLACEMENT"], 95, ["indirect-objects"]],
    ["pronoun-en", "En", "new", "De + noun, partitives and quantities. J’en veux / J’en ai trois / J’en parle. Keep the quantity. Start with food.", ["PRONOUN_SELECTION", "PRONOUN_PLACEMENT"], 90, ["pronoun-y"]],
    ["demonstrative-pronouns", "Celui, celle, ceux, celles", "new", "Celui-ci, celle de Marie; gender and number. Wait until object pronouns are stable.", ["PRONOUN_SELECTION"], 45, ["direct-objects", "indirect-objects"]],
    ["indefinite-words", "Quelqu’un, rien, tout…", "new", "Quelqu’un, quelque chose, personne, rien, chaque, plusieurs, tout/toute/tous/toutes. Introduce gradually.", ["GENDER_NUMBER_AGREEMENT", "VOCABULARY"], 40],
    ["multiple-pronouns", "Multiple pronoun order", "later", "Je le lui donne / Je lui en parle. A2/B1 transition; introduce only when direct/indirect/y/en are individually strong.", ["PRONOUN_PLACEMENT"], 20, ["direct-objects", "indirect-objects", "pronoun-y", "pronoun-en"]],
  ],
  "Adjectives & adverbs": [
    ["adjective-gender", "Adjective gender", "practiced", "Petit/petite, français/française, heureux/heureuse, sportif/sportive.", ["GENDER_NUMBER_AGREEMENT"], 80],
    ["adjective-number", "Adjective number", "practiced", "Feminine plural recurring weakness: Mes sœurs sont heureuses. Missing œ alone is not conceptual failure.", ["GENDER_NUMBER_AGREEMENT"], 95],
    ["irregular-adjectives", "Beau, nouveau, vieux", "practiced", "Beau/belle/bel, nouveau/nouvelle/nouvel, vieux/vieille/vieil; vowel context.", ["GENDER_NUMBER_AGREEMENT"]],
    ["adjective-placement", "Adjective placement", "partial", "Most follow nouns; common beauty/age/number/goodness/size precede. Deux belles maisons, not deux maisons belles. Distinguish placement from agreement.", ["ADJECTIVE_PLACEMENT"], 90],
    ["comparatives", "Comparatives", "new", "Plus/moins/aussi + adjective + que. Contrast mieux and meilleur carefully. Cities, cars, jobs, exercise.", ["GENDER_NUMBER_AGREEMENT", "VOCABULARY"], 83],
    ["superlatives", "Superlatives", "new", "Le/la/les plus/moins; le meilleur/la meilleure. La voiture la plus rapide.", ["GENDER_NUMBER_AGREEMENT"], 81, ["comparatives"]],
    ["adverbs", "Adverbs", "new", "Bien/mal/vite/lentement/rapidement/facilement/souvent/toujours/déjà/encore, then -ment. Placement present and passé composé gradually.", ["ADVERB_PLACEMENT"], 60],
    ["quantities", "Quantity expressions", "new", "Beaucoup de, peu de, un peu de, assez de, trop de, combien de. Beaucoup d’amis, not beaucoup des amis for general quantity.", ["QUANTITY_DE"], 55],
  ],
  "Prepositions": [
    ["a-contractions", "À contractions · au, aux", "practiced", "À + le = au; à + les = aux; à la/à l’ unchanged. Au cinéma, à l’école.", ["PREPOSITION_CONTRACTION"], 75],
    ["de-contractions", "De contractions · du, des", "practiced", "De + le = du; de + les = des. Contrast contractions with partitives.", ["PREPOSITION_CONTRACTION"], 75],
    ["geography", "Cities, countries & regions", "partial", "À Paris, au Colorado; cities/countries/states/regions and origin vs destination. Structured geography practice.", ["GEOGRAPHICAL_PREPOSITION"], 65],
  ],
  "Questions & relative clauses": [
    ["relative-qui", "Relative pronoun qui", "practiced", "Subject of relative clause, people OR things. A verb normally follows; do not teach person = qui.", ["QUI_QUE"]],
    ["relative-que", "Relative pronoun que / qu’", "practiced", "Direct object; another subject usually follows. English ‘that’ is not automatically que.", ["QUI_QUE"], 80],
    ["relative-ou", "Relative pronoun où", "partial", "Place and sometimes time: La ville où j’habite. More practice than qui/que.", ["PRONOUN_SELECTION"]],
    ["qui-que", "Qui vs que", "practiced", "Subject vs object, never person vs thing. Require structure selection.", ["QUI_QUE"], 95],
    ["questions", "Basic question formation", "partial", "Intonation, est-ce que and question words; natural spoken production.", ["QUESTION_STRUCTURE"], 70],
    ["est-ce-que", "Est-ce que or qu’est-ce que?", "partial", "Est-ce que creates yes/no question; qu’est-ce que asks what. Recurring weakness.", ["QUESTION_STRUCTURE"], 85],
    ["quel", "Quel, quelle, quels, quelles", "new", "Which/what agrees with noun: quel livre, quelle voiture, quels films, quelles villes.", ["QUESTION_STRUCTURE", "GENDER_NUMBER_AGREEMENT"], 50],
    ["question-words", "Question words", "new", "Qui/que/quoi/où/quand/comment/pourquoi/combien/quel. Natural spoken alternatives; Avec qui tu travailles ?", ["QUESTION_STRUCTURE"], 48],
  ],
  "Later A2 → B1/B2": [
    ["conditional", "Conditional present", "later", "Je voudrais/j’aimerais/je pourrais/je serais; polite requests before broader conditional uses.", ["VERB_FORM"]],
    ["si-clauses", "Si clauses", "later", "Start si + present → present/future/imperative. Advanced conditionals later.", ["VERB_FORM"], 10, ["futur-simple"]],
    ["dont", "Dont", "later", "Le livre dont je parle: relative pronoun replacing de complement.", ["PRONOUN_SELECTION"]],
    ["lequel", "Lequel family", "later", "Lequel/laquelle/lesquels/lesquelles; then auquel/duquel contractions.", ["PRONOUN_SELECTION"]],
    ["plus-que-parfait", "Plus-que-parfait", "later", "J’avais mangé / j’étais parti; anterior past in context.", ["VERB_FORM"]],
    ["reported-speech", "Reported speech", "later", "Introduce reported statements and questions progressively.", ["VERB_FORM"]],
    ["passive", "Passive voice", "later", "Être + past participle; agreement, agent and communicative use.", ["GENDER_NUMBER_AGREEMENT"]],
    ["subjunctive", "Subjunctive", "later", "Incidental exposure is not learning. Systematic lesson later; do not prioritize now.", ["VERB_FORM"]],
    ["conjunctions", "Advanced conjunctions", "later", "Bien que, afin que, alors que, puisque, quoique; introduce mood contrast after subjunctive.", ["VERB_FORM"], 10, ["subjunctive"]],
    ["advanced-participle", "Advanced participle agreement", "later", "Preceding direct objects/que and reflexive exceptions. Exposed only, not learned.", ["GENDER_NUMBER_AGREEMENT"], 10, ["direct-objects", "pc-agreement"]],
    ["gerund", "En + present participle", "later", "En la voyant was exposure only. Gérondif formation and use later.", ["VERB_FORM"]],
  ],
};

const grammar: Topic[] = Object.entries(groups).flatMap(([group, entries]) => entries.map(([id, title, coverage, notes, tags, priority = 30, prerequisites = []]) => ({ id, title, group, coverage, notes, tags, priority, prerequisites, kind: "grammar" as const })));
const pronunciation = [
  ["u-ou", "U vs ou", "Tu/tout, rue/roue; auditory discrimination before pronunciation."],
  ["nasal", "Nasal vowels", "An/en, on, in/ain/ein."], ["french-r", "French R", "Gentle articulatory guidance; no claims of microphone assessment."],
  ["final-consonants", "Silent final consonants", "Common silent endings and practical exceptions."],
  ["liaison", "Liaison", "Required, optional and forbidden liaison gradually."], ["enchainement", "Enchaînement", "Link pronounced final consonants into following vowel."],
  ["e-vowels", "É, è and e", "Vowel contrast through simple words."], ["schwa", "Disappearing e", "Schwa in natural speech."],
  ["rhythm", "French sentence rhythm", "Rhythmic groups, final stress and intelligibility."], ["reductions", "Spoken-French reductions", "Recognize everyday reduced forms alongside standard writing; TCF listening preparation."],
].map(([id, title, notes]): Topic => ({ id: `sound-${id}`, title, notes, group: "Pronunciation & listening", coverage: "new", priority: 10, tags: ["LISTENING_DISCRIMINATION"], prerequisites: [], kind: "pronunciation" }));
// Explicit IDs preserve existing progress even when entries are reordered or inserted.
const communication = [
  ["communication-1", "Asking for directions"],
  ["communication-2", "Giving directions"],
  ["communication-3", "Making appointments"],
  ["communication-4", "Changing or canceling appointments"],
  ["communication-5", "Doctor and pharmacy"],
  ["communication-6", "Ordering at restaurants"],
  ["communication-7", "Fixing a restaurant order"],
  ["communication-8", "Hotel check-in and check-out"],
  ["communication-9", "Airport conversations"],
  ["communication-10", "Train station conversations"],
  ["communication-11", "Making plans with friends"],
  ["communication-12", "Invitations"],
  ["communication-13", "Accepting invitations"],
  ["communication-14", "Politely refusing invitations"],
  ["communication-15", "Describing appearance"],
  ["communication-16", "Describing personality"],
  ["communication-17", "Describing a home"],
  ["communication-18", "Describing a neighborhood"],
  ["communication-19", "Workplace conversations"],
  ["communication-20", "Phone calls"],
  ["communication-21", "Explaining a problem"],
  ["communication-22", "Asking for help"],
  ["communication-23", "Expressing an opinion"],
  ["communication-24", "Agreeing"],
  ["communication-25", "Disagreeing"],
  ["communication-26", "Comparing choices"],
  ["communication-27", "Advantages and disadvantages"],
  ["communication-28", "Telling a story"],
  ["communication-29", "Explaining reasons"],
  ["communication-30", "Describing goals"],
  ["communication-31", "Future plans"],
  ["communication-32", "Informal messages"],
  ["communication-33", "Simple formal emails"],
  ["communication-34", "Travel problems"],
  ["communication-35", "Shopping returns"],
  ["communication-36", "Talking about experiences"],
  ["communication-37", "Past habits"],
  ["communication-38", "Making recommendations"],
]
  .map(([id, title]): Topic => ({ id, title, notes: `Practical A2 situations for ${title.toLowerCase()}. One prompt at a time; use already covered grammar. Build useful expressions then independent responses.`, group: "Communication", coverage: "new", priority: 10, tags: ["VOCABULARY"], prerequisites: [], kind: "communication" }));

export const TOPICS: Topic[] = [...grammar, ...pronunciation, ...communication];
export const TOPIC_BY_ID = new Map(TOPICS.map((topic) => [topic.id, topic]));
export const LEARNER_CONTEXT = "Late A1 / early A2 grammar coverage; long-term TCF Canada NCLC 7/B2. Food, family, daily routine, time, housing, transport, weather, shopping and sport already encountered. Personal contexts: Colorado/Denver, engineering/work, French class, basketball and exercise. Do not invent personal facts. Coverage is self-reported, with no imported accuracy scores. Prioritize production, concise English grammar explanations and increasingly natural French prompts.";
