// A1-focused French verb seed. ~40 of the most common verbs.
// For irregulars, every verb provides explicit present (and imparfait/futurStem
// when they diverge from the derived defaults). See conjugator.ts for rules.
//
// Vous is conjugated as plural for passé composé with être (masculine plural
// agreement). This is a documented choice — the user's practice modes can
// always add a singular formal variant later.

import type { VerbDef } from "./conjugator";

export const VERBS: VerbDef[] = [
  // ----- Top irregulars (the "big ten") -----
  {
    infinitive: "être",
    english: "to be",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 1,
    present: ["suis", "es", "est", "sommes", "êtes", "sont"],
    imparfait: ["étais", "étais", "était", "étions", "étiez", "étaient"],
    futurStem: "ser",
    pastParticiple: "été",
  },
  {
    infinitive: "avoir",
    english: "to have",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 2,
    present: ["ai", "as", "a", "avons", "avez", "ont"],
    // imparfait from "avons" - "ons" = "av-" → avais, avais, avait, avions, aviez, avaient ✓
    futurStem: "aur",
    pastParticiple: "eu",
  },
  {
    infinitive: "aller",
    english: "to go",
    pattern: "irregular",
    level: "A1",
    auxiliary: "etre",
    frequencyRank: 3,
    present: ["vais", "vas", "va", "allons", "allez", "vont"],
    // imparfait from "allons" - "ons" = "all-" → allais etc. ✓
    futurStem: "ir",
    pastParticiple: "allé",
  },
  {
    infinitive: "faire",
    english: "to do / to make",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 4,
    present: ["fais", "fais", "fait", "faisons", "faites", "font"],
    // imparfait from "faisons" - "ons" = "fais-" → faisais, faisais, faisait, faisions, faisiez, faisaient ✓
    futurStem: "fer",
    pastParticiple: "fait",
  },
  {
    infinitive: "dire",
    english: "to say",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 5,
    present: ["dis", "dis", "dit", "disons", "dites", "disent"],
    futurStem: "dir",
    pastParticiple: "dit",
  },
  {
    infinitive: "pouvoir",
    english: "to be able to / can",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 6,
    present: ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"],
    futurStem: "pourr",
    pastParticiple: "pu",
  },
  {
    infinitive: "vouloir",
    english: "to want",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 7,
    present: ["veux", "veux", "veut", "voulons", "voulez", "veulent"],
    futurStem: "voudr",
    pastParticiple: "voulu",
  },
  {
    infinitive: "venir",
    english: "to come",
    pattern: "irregular",
    level: "A1",
    auxiliary: "etre",
    frequencyRank: 8,
    present: ["viens", "viens", "vient", "venons", "venez", "viennent"],
    futurStem: "viendr",
    pastParticiple: "venu",
  },
  {
    infinitive: "voir",
    english: "to see",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 9,
    present: ["vois", "vois", "voit", "voyons", "voyez", "voient"],
    futurStem: "verr",
    pastParticiple: "vu",
  },
  {
    infinitive: "savoir",
    english: "to know (a fact)",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 10,
    present: ["sais", "sais", "sait", "savons", "savez", "savent"],
    futurStem: "saur",
    pastParticiple: "su",
  },

  // ----- Other essential irregulars -----
  {
    infinitive: "prendre",
    english: "to take",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 11,
    present: ["prends", "prends", "prend", "prenons", "prenez", "prennent"],
    futurStem: "prendr",
    pastParticiple: "pris",
  },
  {
    infinitive: "mettre",
    english: "to put",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 12,
    present: ["mets", "mets", "met", "mettons", "mettez", "mettent"],
    futurStem: "mettr",
    pastParticiple: "mis",
  },
  {
    infinitive: "comprendre",
    english: "to understand",
    pattern: "irregular",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 13,
    present: [
      "comprends",
      "comprends",
      "comprend",
      "comprenons",
      "comprenez",
      "comprennent",
    ],
    futurStem: "comprendr",
    pastParticiple: "compris",
  },
  {
    infinitive: "connaître",
    english: "to know (a person or place)",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 14,
    present: [
      "connais",
      "connais",
      "connaît",
      "connaissons",
      "connaissez",
      "connaissent",
    ],
    futurStem: "connaîtr",
    pastParticiple: "connu",
  },
  {
    infinitive: "partir",
    english: "to leave",
    pattern: "irregular",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 15,
    present: ["pars", "pars", "part", "partons", "partez", "partent"],
    // futurStem default = "partir" ✓
    pastParticiple: "parti",
  },
  {
    infinitive: "sortir",
    english: "to go out",
    pattern: "irregular",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 16,
    present: ["sors", "sors", "sort", "sortons", "sortez", "sortent"],
    pastParticiple: "sorti",
  },
  {
    infinitive: "dormir",
    english: "to sleep",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 17,
    present: ["dors", "dors", "dort", "dormons", "dormez", "dorment"],
    pastParticiple: "dormi",
  },
  {
    infinitive: "devenir",
    english: "to become",
    pattern: "irregular",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 18,
    present: [
      "deviens",
      "deviens",
      "devient",
      "devenons",
      "devenez",
      "deviennent",
    ],
    futurStem: "deviendr",
    pastParticiple: "devenu",
  },
  {
    infinitive: "attendre",
    english: "to wait",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 19,
    present: ["attends", "attends", "attend", "attendons", "attendez", "attendent"],
    // futurStem default = "attendr" ✓
    pastParticiple: "attendu",
  },
  {
    infinitive: "répondre",
    english: "to answer",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 20,
    present: ["réponds", "réponds", "répond", "répondons", "répondez", "répondent"],
    pastParticiple: "répondu",
  },
  {
    infinitive: "vendre",
    english: "to sell",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 21,
    present: ["vends", "vends", "vend", "vendons", "vendez", "vendent"],
    pastParticiple: "vendu",
  },
  {
    infinitive: "écrire",
    english: "to write",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 22,
    present: ["écris", "écris", "écrit", "écrivons", "écrivez", "écrivent"],
    pastParticiple: "écrit",
  },
  {
    infinitive: "lire",
    english: "to read",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 23,
    present: ["lis", "lis", "lit", "lisons", "lisez", "lisent"],
    pastParticiple: "lu",
  },
  {
    infinitive: "boire",
    english: "to drink",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 24,
    present: ["bois", "bois", "boit", "buvons", "buvez", "boivent"],
    // imparfait from "buvons" - "ons" = "buv-" → buvais, buvais, buvait, buvions, buviez, buvaient ✓
    pastParticiple: "bu",
  },

  // ----- Group 1 -er regulars -----
  {
    infinitive: "parler",
    english: "to speak",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 25,
  },
  {
    infinitive: "donner",
    english: "to give",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 26,
  },
  {
    infinitive: "aimer",
    english: "to love / to like",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 27,
  },
  {
    infinitive: "penser",
    english: "to think",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 28,
  },
  {
    infinitive: "trouver",
    english: "to find",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 29,
  },
  {
    infinitive: "regarder",
    english: "to watch",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 30,
  },
  {
    infinitive: "écouter",
    english: "to listen",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 31,
  },
  {
    infinitive: "habiter",
    english: "to live (somewhere)",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 32,
  },
  {
    infinitive: "travailler",
    english: "to work",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 33,
  },
  {
    infinitive: "arriver",
    english: "to arrive",
    pattern: "er",
    level: "A1",
    auxiliary: "etre",
    frequencyRank: 34,
  },
  {
    infinitive: "entrer",
    english: "to enter",
    pattern: "er",
    level: "A1",
    auxiliary: "etre",
    frequencyRank: 35,
  },
  {
    infinitive: "rester",
    english: "to stay",
    pattern: "er",
    level: "A1",
    auxiliary: "etre",
    frequencyRank: 36,
  },

  // ----- Group 1 variants -----
  {
    infinitive: "manger",
    english: "to eat",
    pattern: "er_ger",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 37,
  },
  {
    infinitive: "étudier",
    english: "to study",
    pattern: "er_ier",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 38,
  },

  // ----- Group 2 -ir/-iss- -----
  {
    infinitive: "finir",
    english: "to finish",
    pattern: "ir_iss",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 39,
  },
  {
    infinitive: "choisir",
    english: "to choose",
    pattern: "ir_iss",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 40,
  },

  // ==========================================================
  // Additions from the cheatsheet
  // ==========================================================

  // ----- More irregulars -----
  {
    infinitive: "devoir",
    english: "to have to / must",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 41,
    present: ["dois", "dois", "doit", "devons", "devez", "doivent"],
    futurStem: "devr",
    pastParticiple: "dû",
  },
  {
    infinitive: "descendre",
    english: "to go down",
    pattern: "irregular",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 42,
    present: [
      "descends",
      "descends",
      "descend",
      "descendons",
      "descendez",
      "descendent",
    ],
    // futurStem default = "descendr" ✓
    pastParticiple: "descendu",
  },

  // ----- More regular -er -----
  {
    infinitive: "dîner",
    english: "to dine",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 43,
  },
  {
    infinitive: "chanter",
    english: "to sing",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 44,
  },
  {
    infinitive: "danser",
    english: "to dance",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 45,
  },
  {
    infinitive: "jouer",
    english: "to play",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 46,
  },
  {
    infinitive: "demander",
    english: "to ask",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 47,
  },
  {
    infinitive: "porter",
    english: "to wear / to carry",
    pattern: "er",
    level: "A1",
    auxiliary: "avoir",
    frequencyRank: 48,
  },

  // ----- Quirky -er: stem changes and y→i -----
  {
    // e → è in stressed syllables (singular + 3rd plural). The futur stem
    // keeps the è: achèterai, achèteras, etc.
    infinitive: "acheter",
    english: "to buy",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 49,
    present: ["achète", "achètes", "achète", "achetons", "achetez", "achètent"],
    // imparfait default from "achetons" → "achet-" → achetais, achetions, etc. ✓
    futurStem: "achèter",
    pastParticiple: "acheté",
  },
  {
    // y → i in singular + 3rd plural. Both forms (je paye/je paie) are
    // accepted; we use the more common "i" variant.
    infinitive: "payer",
    english: "to pay",
    pattern: "irregular",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 50,
    present: ["paie", "paies", "paie", "payons", "payez", "paient"],
    // imparfait from "payons" → "pay-" → payais, payions, etc. ✓
    futurStem: "paier",
    pastParticiple: "payé",
  },

  // ----- Reflexive -er -----
  {
    infinitive: "se réveiller",
    english: "to wake up",
    pattern: "er_reflexive",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 51,
  },
  {
    infinitive: "se coucher",
    english: "to go to bed",
    pattern: "er_reflexive",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 52,
  },
  {
    infinitive: "s'habiller",
    english: "to get dressed",
    pattern: "er_reflexive",
    level: "A2",
    auxiliary: "etre",
    frequencyRank: 53,
  },

  // ----- More group 2 -ir/-iss- -----
  {
    infinitive: "réussir",
    english: "to succeed",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 54,
  },
  {
    infinitive: "grandir",
    english: "to grow up",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 55,
  },
  {
    infinitive: "grossir",
    english: "to gain weight",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 56,
  },
  {
    infinitive: "maigrir",
    english: "to lose weight",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 57,
  },
  {
    infinitive: "rougir",
    english: "to blush",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 58,
  },
  {
    infinitive: "obéir",
    english: "to obey",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 59,
  },
  {
    infinitive: "réfléchir",
    english: "to reflect / to think",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 60,
  },
  {
    infinitive: "remplir",
    english: "to fill",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 61,
  },
  {
    infinitive: "punir",
    english: "to punish",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 62,
  },
  {
    infinitive: "bâtir",
    english: "to build",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 63,
  },
  {
    infinitive: "guérir",
    english: "to heal / to cure",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 64,
  },
  {
    infinitive: "applaudir",
    english: "to applaud",
    pattern: "ir_iss",
    level: "A2",
    auxiliary: "avoir",
    frequencyRank: 65,
  },
];
