"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, Loader2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
interface Facts { weekStart: string; added: number; totalAttempts: number; production: { attempts: number; correct: number; percent: number | null }; listening: { attempts: number; correct: number; percent: number | null }; hardOrAgain: number; naturalTutorUses: number }
interface Summary { headline: string; reflection: string; nextFocus: string }
export default function WeeklyPage() { const [facts, setFacts] = useState<Facts | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [summaryStale, setSummaryStale] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const load = () => fetch("/api/weekly-review", { cache: "no-store" }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); setFacts(d.facts); setSummary(d.summary); setSummaryStale(Boolean(d.summaryStale)); }).catch(e => setError(String(e))); useEffect(() => { void load(); }, []); const generate = async () => { setBusy(true); setError(""); try { const r = await fetch("/api/weekly-review", { method: "POST" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setFacts(d.facts); setSummary(d.summary); setSummaryStale(false); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }; return <main className="container max-w-2xl py-7">
  <Link href="/" className="mb-5 inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Home</Link><h1 className="flex items-center gap-2 text-3xl font-semibold"><CalendarDays className="h-7 w-7"/>Weekly review</h1><p className="mb-6 text-muted-foreground">A quiet look at this week&apos;s evidence and what to carry forward.</p>
  {!facts ? <div className="h-48 animate-pulse rounded-xl bg-muted"/> : <><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Attempts", facts.totalAttempts], ["Production", facts.production.percent === null ? "—" : `${facts.production.percent}%`], ["Listening", facts.listening.percent === null ? "—" : `${facts.listening.percent}%`], ["Natural uses", facts.naturalTutorUses]].map(([label, value]) => <Card key={label}><CardContent className="p-4"><div className="text-2xl font-semibold">{value}</div><div className="text-xs text-muted-foreground">{label}</div></CardContent></Card>)}</div>
    <Card className="mt-4"><CardContent className="space-y-2 p-5 text-sm"><p><b>{facts.added}</b> lesson items added</p><p><b>{facts.hardOrAgain}</b> answers worth another look</p><p className="text-muted-foreground">Week beginning {new Date(facts.weekStart).toLocaleDateString()}</p></CardContent></Card>
    <Card className="mt-4"><CardHeader><CardTitle className="text-lg">Reflection</CardTitle></CardHeader><CardContent>{summary ? <div className="space-y-3">{summaryStale && <p className="rounded-md bg-amber-500/10 px-3 py-2 text-xs text-amber-700 dark:text-amber-300">Based on earlier facts from this week. Regenerate to include your latest practice.</p>}<h2 className="font-semibold">{summary.headline}</h2><p className="text-sm">{summary.reflection}</p><div className="rounded-lg bg-muted p-3 text-sm"><b>Next focus:</b> {summary.nextFocus}</div>{summaryStale && <Button onClick={generate} disabled={busy}>{busy ? <Loader2 className="h-4 w-4 animate-spin"/> : <Sparkles className="h-4 w-4"/>}Refresh summary</Button>}</div> : <><p className="mb-4 text-sm text-muted-foreground">Generate a short reflection with your enabled Codex/Claude provider. It runs only when you tap.</p><Button onClick={generate} disabled={busy}>{busy ? <Loader2 className="h-4 w-4 animate-spin"/> : <Sparkles className="h-4 w-4"/>}Generate summary</Button></>}</CardContent></Card></>}
  {error && <p className="mt-4 text-sm text-destructive">{error}</p>}
  </main>; }
