#!/usr/bin/env python3
"""Private, allowlisted Docs text editor bridge. JSON on stdin/stdout; no secrets out."""
import difflib
import fcntl
import json
import os
from pathlib import Path
import sys

CONFIG = Path.home() / ".hermes/french-google-docs.json"
PERSONAL = Path.home() / ".hermes/french-personal-notes.json"
WRITE_SCOPE = "https://www.googleapis.com/auth/documents"


class EditorError(Exception):
    def __init__(self, message, status=400):
        super().__init__(message)
        self.status = status


def utf16(text):
    return len(text.encode("utf-16-le")) // 2


def blocks(contents, table=False):
    for element in contents:
        if "paragraph" in element:
            paragraph = element["paragraph"]
            parts = paragraph.get("elements", [])
            runs = [{"text": p.get("textRun", {}).get("content", ""),
                     "bold": bool(p.get("textRun", {}).get("textStyle", {}).get("bold")),
                     "italic": bool(p.get("textRun", {}).get("textStyle", {}).get("italic")),
                     "strike": bool(p.get("textRun", {}).get("textStyle", {}).get("strikethrough"))}
                    for p in parts]
            text = "".join(r["text"] for r in runs)
            # Never delete the structural newline or edit objects/suggestions as plain text.
            editable = bool(parts) and text.endswith("\n") and all(
                "textRun" in p and not any("suggest" in k.lower() for k in p)
                and not any("suggest" in k.lower() for k in p["textRun"]) for p in parts)
            editable = editable and not any("suggest" in k.lower() for k in paragraph)
            start = element.get("startIndex", 0)
            editable = editable and start > 0 and utf16(text) == element.get("endIndex", 0) - start
            yield {"start": start, "text": text[:-1] if text.endswith("\n") else text,
                   "runs": runs, "editable": editable, "table": table,
                   "heading": paragraph.get("paragraphStyle", {}).get("namedStyleType", "NORMAL_TEXT")}
        for row in element.get("table", {}).get("tableRows", []):
            for cell in row.get("tableCells", []):
                yield from blocks(cell.get("content", []), True)
        # Table-of-contents content is generated by Google; do not offer edits.


def present(document, can_write):
    result = []
    def walk(tabs):
        for tab in tabs:
            props = tab.get("tabProperties", {})
            content = tab.get("documentTab", {}).get("body", {}).get("content", [])
            result.append({"id": props.get("tabId", ""), "title": props.get("title", "Notes"),
                           "blocks": list(blocks(content))})
            walk(tab.get("childTabs", []))
    walk(document.get("tabs", []))
    if not result:
        result.append({"id": "", "title": "Notes", "blocks": list(blocks(document.get("body", {}).get("content", [])))})
    return {"id": document["documentId"], "title": document.get("title", "Notes").strip(),
            "revision": document.get("revisionId"),
            "canWrite": can_write and bool(document.get("revisionId")), "tabs": result}


def edit_requests(block, new_text, tab_id):
    """Apply only changed ranges, descending, keeping unchanged runs and UTF-16 indices."""
    old = block["text"]
    requests = []
    for tag, i, j, a, b in reversed(difflib.SequenceMatcher(None, old, new_text, autojunk=False).get_opcodes()):
        if tag == "equal":
            continue
        start = block["start"] + utf16(old[:i])
        if j > i:
            requests.append({"deleteContentRange": {"range": {
                "startIndex": start, "endIndex": block["start"] + utf16(old[:j]), "tabId": tab_id}}})
        if b > a:
            requests.append({"insertText": {"location": {"index": start, "tabId": tab_id}, "text": new_text[a:b]}})
    return requests


class Google:
    def __init__(self, config):
        import requests
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request
        self.http = requests.Session()
        credentials = Credentials.from_authorized_user_file(config["google_token_file"])
        self.can_write = WRITE_SCOPE in (credentials.scopes or [])
        if not credentials.valid:
            credentials.refresh(Request())
        # Keep refreshed tokens in memory, avoiding races with the weekly sync token writer.
        self.headers = {"Authorization": "Bearer " + credentials.token}

    def request(self, method, suffix, payload=None):
        response = self.http.request(method, "https://docs.googleapis.com/v1/documents" + suffix,
                                     headers=self.headers, json=payload, timeout=35)
        if not response.ok:
            if response.status_code == 403:
                raise EditorError("Google denied access. Check editor sharing permission and reconnect with Google Docs write access.", 403)
            if response.status_code == 404:
                raise EditorError("This document is unavailable to the connected Google account.", 404)
            if response.status_code == 400 and ":batchUpdate" in suffix:
                raise EditorError("Google could not apply this edit. The document may have changed. Your draft is kept; reload the document before trying again.", 409)
            raise EditorError("Google Docs is unavailable. Your draft is kept; try again shortly.", 502)
        return response.json()

    def get(self, doc_id):
        return self.request("GET", "/" + doc_id + "?includeTabsContent=true")


def personal_id(path=PERSONAL):
    return json.loads(path.read_text())["documentId"] if path.exists() else None


def handle(body, config, google, personal_path=PERSONAL):
    personal = personal_id(personal_path)
    ids = list(config["document_ids"][:2])
    if personal:
        ids.append(personal)
    action = body.get("action")
    if action == "list":
        return {"canWrite": google.can_write, "documents": [
            {"id": value, "label": "Personal Notes" if value == personal else f"italki notes {index + 1}"}
            for index, value in enumerate(ids)], "hasPersonal": bool(personal)}
    if action == "create":
        if not google.can_write:
            raise EditorError("Connect Google Docs write access to create Personal Notes.", 403)
        # A persistent lock also protects against double clicks/concurrent browser tabs.
        with personal_path.with_suffix(".lock").open("a") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            personal = personal_id(personal_path)
            if not personal:
                created = google.request("POST", "", {"title": "Personal French Notes"})
                personal = created["documentId"]
                temporary = personal_path.with_suffix(".tmp")
                fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
                with os.fdopen(fd, "w") as stream:
                    json.dump({"documentId": personal}, stream)
                os.replace(temporary, personal_path)
            return {"id": personal}
    doc_id = body.get("id")
    if doc_id not in ids:
        raise EditorError("This document is not connected to French Tutor.", 403)
    document = present(google.get(doc_id), google.can_write)
    if action == "get":
        return document
    if action not in ("edit", "append"):
        raise EditorError("Unknown editor action.")
    if not document["canWrite"]:
        raise EditorError("Connect Google Docs write access and check that your tutor shared this document with Editor permission.", 403)
    if not body.get("revision") or document["revision"] != body["revision"]:
        raise EditorError("This document changed since you opened it. Your draft is kept; reload and compare before saving.", 409)
    tab = next((tab for tab in document["tabs"] if tab["id"] == body.get("tabId")), None)
    if tab is None:
        raise EditorError("Document tab not found.")
    text = body.get("text")
    if not isinstance(text, str) or len(text) > 10000 or any(ord(c) < 32 and c not in "\n\t" for c in text):
        raise EditorError("Use up to 10,000 characters of text.")
    if action == "append":
        if not text.strip():
            raise EditorError("Write a note first.")
        requests = [{"insertText": {"endOfSegmentLocation": {"tabId": tab["id"]}, "text": "\n" + text + "\n"}}]
    else:
        block = next((b for b in tab["blocks"] if b["start"] == body.get("start")), None)
        if not block or not block["editable"]:
            raise EditorError("This paragraph contains formatting or objects that must be edited in Google Docs.")
        requests = edit_requests(block, text, tab["id"])
    if requests:
        google.request("POST", "/" + doc_id + ":batchUpdate", {
            "writeControl": {"requiredRevisionId": body["revision"]}, "requests": requests})
    # Return an acknowledgement before any follow-up read can fail after a successful write.
    return {"saved": True}


if __name__ == "__main__":
    try:
        config = json.loads(CONFIG.read_text())
        result = handle(json.load(sys.stdin), config, Google(config))
        print(json.dumps(result, ensure_ascii=False))
    except EditorError as error:
        print(json.dumps({"error": str(error), "status": error.status}))
    except Exception:
        # OAuth/library failures can contain credentials or source text. Never echo them.
        print(json.dumps({"error": "Could not connect to Google Docs. Your draft is kept; check the Google connection and try again.", "status": 502}))
